import Head from "next/head";
import React from "react";

const Meta = ({ title, desc }) => {
	return (
		<>
			<Head>
				<title>infinity24 | {title}</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
		</>
	);
};

Meta.defaultProps = {
	title: "home page",
	desc: "Generated by create next app",
};

export default Meta;
